"""Generated by scripts/scoring_fingerprint.py -- do not edit by hand.

Identifies the scoring code that produced a model artifact. Regenerate with
`python scripts/scoring_fingerprint.py --write` after changing any file in that
script's MANIFEST.
"""

SCORING_FINGERPRINT = "2116f4c3e2cf35e6"
