// Generated by scripts/scoring_fingerprint.py -- do not edit by hand.
//
// Identifies the scoring code that produced a model artifact. Regenerate with
// `python scripts/scoring_fingerprint.py --write` after changing any file in
// that script's MANIFEST.

package main

const scoringFingerprint = "e216ccec3f7ec07c"
