"""The watch-time response curve is fitted per instance, and refuses to adopt.

The shipped curve rises monotonically in watch time; measured against whether
the user returned to a scene on a later day, the real relationship is an
inverted U peaking near a minute. These cover the fit, the guards that keep a
cold install on the shipped curve, and the fixture the Go mirror reproduces.
"""

from __future__ import annotations

import math

import pytest

from curator.events.curves import view_value, viewing_outcome
from curator.model.watchfit import (
    DEFAULT_VIEW_CURVE,
    MIN_FIRST_PLAYS,
    fit_view_curve,
)

# Deterministic corpus, generated by integer arithmetic so core/watchfit_test.go
# can build the identical sample set without sharing a fixture file.
TRUE_CURVE = (-4.0, 1.6, -0.2)


def parity_corpus(count: int = 600) -> list[tuple[float, bool]]:
    samples: list[tuple[float, bool]] = []
    state = 12345
    for index in range(count):
        seconds = math.exp(1.5 + 6.5 * ((index % 64) / 64.0))
        log_t = math.log(seconds)
        z = TRUE_CURVE[0] + TRUE_CURVE[1] * log_t + TRUE_CURVE[2] * log_t * log_t
        probability = 1.0 / (1.0 + math.exp(-z))
        state = (state * 1103515245 + 12345) % 2147483648
        samples.append((seconds, (state / 2147483648.0) < probability))
    return samples


def test_fit_recovers_an_inverted_u() -> None:
    fit = fit_view_curve(parity_corpus())

    assert fit.adopted, fit.reason
    assert fit.coefficients[2] < 0.0, "an inverted U requires negative curvature"
    peak = math.exp(-fit.coefficients[1] / (2.0 * fit.coefficients[2]))
    assert 20.0 < peak < 200.0, f"peak at {peak:.1f}s is not near a minute"


def test_quadratic_must_win_on_held_out_data() -> None:
    """'It won', not 'it converged'."""
    fit = fit_view_curve(parity_corpus())

    assert fit.heldout_quadratic < fit.heldout_monotone
    assert fit.heldout_quadratic < fit.heldout_constant


def test_small_sample_keeps_the_shipped_curve() -> None:
    fit = fit_view_curve(parity_corpus(MIN_FIRST_PLAYS - 1))

    assert fit.adopted is False
    assert fit.reason == "insufficient_sample"
    assert fit.coefficients == DEFAULT_VIEW_CURVE


def test_too_few_positives_keeps_the_shipped_curve() -> None:
    fit = fit_view_curve([(seconds, False) for seconds, _ in parity_corpus()])

    assert fit.adopted is False
    assert fit.reason == "insufficient_positives"
    assert fit.coefficients == DEFAULT_VIEW_CURVE


def test_no_relationship_is_refused() -> None:
    """A duration that carries no signal must not displace the shipped curve."""
    samples = [(seconds, index % 5 == 0) for index, (seconds, _) in enumerate(parity_corpus())]

    fit = fit_view_curve(samples)

    assert fit.adopted is False
    assert fit.coefficients == DEFAULT_VIEW_CURVE


def test_shrinkage_pulls_toward_the_shipped_prior() -> None:
    """A smaller instance must sit closer to the shipped curve than a larger
    one, so behaviour moves smoothly rather than jumping between builds."""
    big = fit_view_curve(parity_corpus(2000))
    small = fit_view_curve(parity_corpus(260))
    assert big.adopted and small.adopted

    def distance(fit: object) -> float:
        coefficients = fit.coefficients  # type: ignore[attr-defined]
        return sum((coefficients[i] - DEFAULT_VIEW_CURVE[i]) ** 2 for i in range(3))

    assert distance(small) < distance(big)


def test_fitted_curve_orders_by_measured_outcome() -> None:
    """The defect in one line: the shipped curve scores a long play far above a
    one-minute play, and the fitted curve does not."""
    fit = fit_view_curve(parity_corpus()).curve

    assert view_value(45.0) < view_value(600.0), "shipped curve rises monotonically"
    assert _positive(view_value(45.0, view_curve=fit)) > _value_or_zero(
        view_value(600.0, view_curve=fit)
    )


def test_fitted_curve_stays_inside_the_shipped_output_range() -> None:
    fit = fit_view_curve(parity_corpus()).curve

    for seconds in (1.0, 5.0, 30.0, 45.0, 90.0, 300.0, 1800.0, 7200.0):
        value = view_value(seconds, view_curve=fit)
        if value is not None:
            assert -0.10 <= value <= 0.35


def test_short_plays_are_negative_evidence() -> None:
    """The measured return rate under the lower crossover sits far below the
    library average, so a brief play is evidence against, not evidence absent."""
    fit = fit_view_curve(parity_corpus()).curve

    assert _positive(view_value(2.0, view_curve=fit)) < 0.0
    assert _positive(view_value(5.0, view_curve=fit)) < 0.0


def test_long_plays_decay_to_a_small_positive_floor() -> None:
    """Past the peak the parabola keeps falling, but measured return rates out
    there are indistinguishable from the base rate. A long play is still
    engagement, so the limb settles low rather than going to nothing or to
    dislike -- and a scene whose only evidence is one long play keeps a label."""
    fit = fit_view_curve(parity_corpus()).curve

    far = _positive(view_value(36000.0, view_curve=fit))
    near = _positive(view_value(600.0, view_curve=fit))

    assert far == pytest.approx(0.05, abs=1e-6)
    assert far < near < 0.35, "the right limb must decay, not step"
    assert viewing_outcome(36000.0, 0, historical_imputed=True, view_curve=fit) is not None


def test_right_limb_is_monotone_and_never_negative() -> None:
    fit = fit_view_curve(parity_corpus()).curve
    peak = math.exp(-fit[1] / (2.0 * fit[2]))
    previous = None
    seconds = peak
    while seconds < 100000.0:
        value = _positive(view_value(seconds, view_curve=fit))
        assert value >= 0.05 - 1e-9
        if previous is not None:
            assert value <= previous + 1e-12, f"not decaying at {seconds:.0f}s"
        previous = value
        seconds *= 1.05


def test_there_is_no_step_at_the_short_exit_threshold() -> None:
    """The whole point of centring on the base rate: 29.9s and 30.1s must not
    differ by most of the signal's range, as they did with a refitted rise."""
    fit = fit_view_curve(parity_corpus()).curve

    below = _positive(view_value(29.9, view_curve=fit))
    above = _positive(view_value(30.1, view_curve=fit))

    assert abs(above - below) < 0.01


def test_curve_is_continuous() -> None:
    """No jump anywhere the curve returns a value."""
    fit = fit_view_curve(parity_corpus()).curve
    previous = None
    seconds = 1.0
    while seconds < 600.0:
        value = view_value(seconds, view_curve=fit)
        if value is not None and previous is not None:
            assert abs(value - previous) < 0.02, f"jump at {seconds:.1f}s"
        previous = value
        seconds *= 1.02


def test_imputed_short_play_is_negative_only_once_fitted() -> None:
    """The shipped curve refuses to read an averaged duration as dislike; a
    fitted curve does, with the discount carried by confidence instead."""
    fit = fit_view_curve(parity_corpus()).curve

    assert viewing_outcome(5.0, 0, historical_imputed=True) is None

    signal = viewing_outcome(5.0, 0, historical_imputed=True, view_curve=fit)
    assert signal is not None
    assert signal.value < 0.0
    assert signal.confidence == 0.45


def test_repeat_evidence_outranks_the_negative_view_floor() -> None:
    """A scene played briefly but often must not read as disliked."""
    from curator.events.curves import collapse_signals, repeat_outcome

    fit = fit_view_curve(parity_corpus()).curve
    brief = viewing_outcome(5.0, 0, historical_imputed=True, view_curve=fit)
    repeat = repeat_outcome(48.0, 0)
    assert brief is not None and repeat is not None

    collapsed = collapse_signals([brief, repeat])

    assert collapsed is not None
    assert collapsed.primary_signal == "repeat"
    assert collapsed.value > 0.0


def test_unfitted_curve_is_the_shipped_curve() -> None:
    for seconds in (30.0, 60.0, 300.0, 3600.0):
        assert view_value(seconds, view_curve=None) == 0.35 * (
            1 - math.exp(-(seconds - 30.0) / 90.0)
        )
    assert view_value(15.0, view_curve=None) == -0.10 * (1 - 15.0 / 30.0)


def test_missing_duration_abstains_rather_than_scoring_dislike() -> None:
    """Most directly observed sessions never record a duration, so a zero must
    not be read as the strongest available dislike."""
    fit = fit_view_curve(parity_corpus()).curve

    assert view_value(0.0, view_curve=fit) is None
    assert viewing_outcome(0.0, 0, view_curve=fit) is None
    assert viewing_outcome(0.0, 0, historical_imputed=True, view_curve=fit) is None


def _positive(value: float | None) -> float:
    assert value is not None
    return value


def _value_or_zero(value: float | None) -> float:
    return 0.0 if value is None else value
