"""The watch-time response curve is fitted per instance, and refuses to adopt.

The shipped curve rises monotonically in watch time; measured against whether
the user returned to a scene on a later day, the real relationship is an
inverted U peaking near a minute. These cover the fit, the guards that keep a
cold install on the shipped curve, and the fixture the Go mirror reproduces.
"""

from __future__ import annotations

import math

from curator.events.curves import view_rise, viewing_outcome
from curator.model.watchfit import (
    DEFAULT_VIEW_CURVE,
    MIN_FIRST_PLAYS,
    fit_view_curve,
)

# Deterministic corpus, generated by integer arithmetic so core/watchfit_test.go
# can build the identical sample set without sharing a fixture file.
TRUE_CURVE = (-4.0, 1.6, -0.2)


def parity_corpus(count: int = 600) -> list[tuple[float, bool]]:
    samples: list[tuple[float, bool]] = []
    state = 12345
    for index in range(count):
        seconds = math.exp(1.5 + 6.5 * ((index % 64) / 64.0))
        log_t = math.log(seconds)
        z = TRUE_CURVE[0] + TRUE_CURVE[1] * log_t + TRUE_CURVE[2] * log_t * log_t
        probability = 1.0 / (1.0 + math.exp(-z))
        state = (state * 1103515245 + 12345) % 2147483648
        samples.append((seconds, (state / 2147483648.0) < probability))
    return samples


def test_fit_recovers_an_inverted_u() -> None:
    fit = fit_view_curve(parity_corpus())

    assert fit.adopted, fit.reason
    assert fit.coefficients[2] < 0.0, "an inverted U requires negative curvature"
    peak = math.exp(-fit.coefficients[1] / (2.0 * fit.coefficients[2]))
    assert 20.0 < peak < 200.0, f"peak at {peak:.1f}s is not near a minute"


def test_quadratic_must_win_on_held_out_data() -> None:
    """'It won', not 'it converged'."""
    fit = fit_view_curve(parity_corpus())

    assert fit.heldout_quadratic < fit.heldout_monotone
    assert fit.heldout_quadratic < fit.heldout_constant


def test_small_sample_keeps_the_shipped_curve() -> None:
    fit = fit_view_curve(parity_corpus(MIN_FIRST_PLAYS - 1))

    assert fit.adopted is False
    assert fit.reason == "insufficient_sample"
    assert fit.coefficients == DEFAULT_VIEW_CURVE


def test_too_few_positives_keeps_the_shipped_curve() -> None:
    fit = fit_view_curve([(seconds, False) for seconds, _ in parity_corpus()])

    assert fit.adopted is False
    assert fit.reason == "insufficient_positives"
    assert fit.coefficients == DEFAULT_VIEW_CURVE


def test_no_relationship_is_refused() -> None:
    """A duration that carries no signal must not displace the shipped curve."""
    samples = [(seconds, index % 5 == 0) for index, (seconds, _) in enumerate(parity_corpus())]

    fit = fit_view_curve(samples)

    assert fit.adopted is False
    assert fit.coefficients == DEFAULT_VIEW_CURVE


def test_shrinkage_pulls_toward_the_shipped_prior() -> None:
    """A smaller instance must sit closer to the shipped curve than a larger
    one, so behaviour moves smoothly rather than jumping between builds."""
    big = fit_view_curve(parity_corpus(2000))
    small = fit_view_curve(parity_corpus(260))
    assert big.adopted and small.adopted

    def distance(fit: object) -> float:
        coefficients = fit.coefficients  # type: ignore[attr-defined]
        return sum((coefficients[i] - DEFAULT_VIEW_CURVE[i]) ** 2 for i in range(3))

    assert distance(small) < distance(big)


def test_fitted_curve_orders_by_measured_outcome() -> None:
    """The defect in one line: the shipped curve scores a long play far above a
    one-minute play, and the fitted curve does not."""
    fit = fit_view_curve(parity_corpus()).coefficients

    assert view_rise(45.0) < view_rise(600.0), "shipped curve rises monotonically"
    assert view_rise(45.0, view_curve=fit) > view_rise(600.0, view_curve=fit)


def test_fitted_curve_stays_inside_the_shipped_output_range() -> None:
    fit = fit_view_curve(parity_corpus()).coefficients

    for seconds in (30.0, 45.0, 90.0, 300.0, 1800.0, 7200.0):
        assert 0.0 <= view_rise(seconds, view_curve=fit) <= 0.35


def test_fitted_curve_does_not_erase_view_labels() -> None:
    """A mapping that drives the tail to exactly zero silently deletes labels,
    because viewing_outcome drops a signal that rounds to zero."""
    fit = fit_view_curve(parity_corpus()).coefficients
    durations = [30.0 + 15.0 * step for step in range(200)]

    dropped = sum(
        1
        for seconds in durations
        if viewing_outcome(seconds, 0, historical_imputed=True, view_curve=fit) is None
    )

    assert dropped == 0


def test_unfitted_curve_is_the_shipped_curve() -> None:
    for seconds in (30.0, 60.0, 300.0, 3600.0):
        assert view_rise(seconds, view_curve=None) == 0.35 * (
            1 - math.exp(-(seconds - 30.0) / 90.0)
        )
