#!/usr/bin/env python3
"""Derive the scoring-code fingerprint that identifies a model artifact.

`model_digest` hashes source *data* and config, so an algorithm change with
unchanged inputs used to produce an identical `model_id`: the build found the
published row, incremented `reuse_count`, and served the previous algorithm's
artifact. This makes code identity part of the key.

The fingerprint covers both implementations at once — the Go binary that
actually builds artifacts and the Python differential oracle — because the
digest is a mirrored pair that has to stay byte-identical on both sides. One
shared constant is the only way both can agree without each hashing sources the
other cannot see.

MANIFEST lists the files whose content decides what lands *in* the artifact.
Serve-time code (`slate.py`, `core/slate*.go`, `explanations*.go`) is
deliberately excluded: it re-reads the artifact per request and changing it does
not make a stored model stale. Config constants are already covered by
`config.canonical_json()`, and feature semantics by `feature_version`.

Run with --write to regenerate the two generated constants after changing any
manifest file; `tests/model/test_scoring_fingerprint.py` fails until you do.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Files whose content determines the artifact's contents. Keep sorted.
MANIFEST = (
    "core/eligibility.go",
    "core/laneclassify.go",
    "core/materialize.go",
    "core/modelbuild.go",
    "core/modelbuild2.go",
    "core/modelbuild3.go",
    "core/multi_hop.go",
    "core/multihop.go",
    "curator/model/boundaries.py",
    "curator/model/builder.py",
    "curator/model/curves.py",
    "curator/model/multi_hop.py",
    "curator/ranking/policy.py",
)

# The generated files themselves are excluded from MANIFEST: they hold the
# fingerprint, so including them would make the hash self-referential.
PYTHON_TARGET = "curator/model/fingerprint.py"
GO_TARGET = "core/scoring_fingerprint.go"

FINGERPRINT_LENGTH = 16

PYTHON_TEMPLATE = '''"""Generated by scripts/scoring_fingerprint.py -- do not edit by hand.

Identifies the scoring code that produced a model artifact. Regenerate with
`python scripts/scoring_fingerprint.py --write` after changing any file in that
script's MANIFEST.
"""

SCORING_FINGERPRINT = "{fingerprint}"
'''

GO_TEMPLATE = """// Generated by scripts/scoring_fingerprint.py -- do not edit by hand.
//
// Identifies the scoring code that produced a model artifact. Regenerate with
// `python scripts/scoring_fingerprint.py --write` after changing any file in
// that script's MANIFEST.

package main

const scoringFingerprint = "{fingerprint}"
"""


def compute(root: Path = REPO_ROOT) -> str:
    """Hash every manifest file's path and content, in manifest order."""
    digest = hashlib.sha256()
    for relative in MANIFEST:
        path = root / relative
        if not path.is_file():
            raise SystemExit(f"scoring fingerprint: manifest file is missing: {relative}")
        # Normalize line endings so a CRLF checkout does not rebuild every model.
        content = path.read_bytes().replace(b"\r\n", b"\n")
        digest.update(relative.encode())
        digest.update(b"\0")
        digest.update(content)
        digest.update(b"\0")
    return digest.hexdigest()[:FINGERPRINT_LENGTH]


def render(fingerprint: str) -> dict[str, str]:
    return {
        PYTHON_TARGET: PYTHON_TEMPLATE.format(fingerprint=fingerprint),
        GO_TARGET: GO_TEMPLATE.format(fingerprint=fingerprint),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="rewrite the generated constants instead of only printing the fingerprint",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the generated constants are stale",
    )
    args = parser.parse_args(argv)

    fingerprint = compute()
    rendered = render(fingerprint)

    if args.write:
        for relative, content in rendered.items():
            (REPO_ROOT / relative).write_text(content)
        print(f"wrote {fingerprint} to {', '.join(rendered)}")
        return 0

    if args.check:
        stale = [
            relative
            for relative, content in rendered.items()
            if (REPO_ROOT / relative).read_text() != content
        ]
        if stale:
            print(
                f"scoring fingerprint is stale ({fingerprint}); "
                f"run scripts/scoring_fingerprint.py --write to update {', '.join(stale)}",
                file=sys.stderr,
            )
            return 1
        print(f"scoring fingerprint up to date ({fingerprint})")
        return 0

    print(fingerprint)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
